name: Restart Bot Server

on:
  push:
    branches:
      - main

jobs:
  restart:
    runs-on: ubuntu-latest

    steps:
      - name: Restart Pterodactyl Server
        run: |
          curl -X POST \
            "https://panel.gamehoster.fi/api/client/servers/${{ secrets.SERVER_ID }}/power" \
            -H "Authorization: Bearer ${{ secrets.PTERO_API_KEY }}" \
            -H "Accept: Application/vnd.pterodactyl.v1+json" \
            -H "Content-Type: application/json" \
            -d '{"signal":"restart"}'